// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDefaultProject() {
  return window['go']['main']['App']['GetDefaultProject']();
}

export function GetEpics(arg1) {
  return window['go']['main']['App']['GetEpics'](arg1);
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetTemplates() {
  return window['go']['main']['App']['GetTemplates']();
}

export function RunGojitzu(arg1) {
  return window['go']['main']['App']['RunGojitzu'](arg1);
}

export function RunGojitzuAsync(arg1) {
  return window['go']['main']['App']['RunGojitzuAsync'](arg1);
}
