// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDefaultProject():Promise<string>;

export function GetEpics(arg1:string):Promise<Record<string, any>>;

export function GetProjects():Promise<Record<string, any>>;

export function GetTemplates():Promise<Record<string, any>>;

export function RunGojitzu(arg1:Array<string>):Promise<string>;

export function RunGojitzuAsync(arg1:Array<string>):Promise<void>;
